name: foodsplash
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0' # Menggunakan rentang versi Dart

dependencies:
  flutter:
    sdk: flutter
  
  # Package yang digabungkan dari kedua versi:
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  http: ^1.5.0
  flutter_svg: ^2.0.9
  provider: ^6.1.5
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    # Tambahkan direktori vectors jika Anda menggunakannya untuk SVG:
    # - assets/vectors/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section.
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600